upload_data_homepage:
    path:     /
    defaults: { _controller: UploadDataBundle:Dashboard:index }

_upload_data_upload:
    resource: routing/upload.yml
    prefix: /{type}

_upload_data_upload_read:
    resource: routing/read.yml
    prefix: /read
    condition: request.isXmlHttpRequest()