upload_data_homepage:
    path:     /
    defaults: { _controller: UploadDataBundle:Dashboard:index }

upload_data_upload_list:
    path:     /{type}/list
    defaults: { _controller: UploadDataBundle:Upload:list }

upload_data_upload_show:
    path:     /{type}/show/{id}
    defaults: { _controller: UploadDataBundle:Upload:show }

upload_data_upload_new:
    path:     /{type}/new
    defaults: { _controller: UploadDataBundle:Upload:new }

upload_data_upload_read:
    path:     /{type}/read/{id}
    defaults: { _controller: UploadDataBundle:Upload:read }

upload_data_upload_validate:
    path:     /{type}/validate/{id}
    defaults: { _controller: UploadDataBundle:Upload:validate }

upload_data_upload_transfer:
    path:     /{type}/transfer/{id}
    defaults: { _controller: UploadDataBundle:Upload:transfer }
