upload_data_homepage:
    path:     /
    defaults: { _controller: UploadDataBundle:Dashboard:index }

_upload_controller:
    resource: @UploadDataBundle/Controller/UploadController.php
    type: annotation

_upload_csv_read_controller:
    resource: @UploadDataBundle/Controller/CsvReadController.php
    type: annotation

_upload_excel_read_controller:
    resource: @UploadDataBundle/Controller/ExcelReadController.php
    type: annotation
