services:
#    upload_data.example:
#        class: Manuel\Bundle\UploadDataBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    upload_data.config_provider:
        class: Manuel\Bundle\UploadDataBundle\ConfigProvider
        arguments: [@service_container, []]

    upload_data.column_list_factory:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\ColumnFactory
        arguments: [@service_container, []]

    upload_data.list_mapper:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ListMapper
        arguments: [@upload_data.column_list_factory]
        public: false

    upload_data.column_list.text:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\TextColumn
        tags:
            - { name: upload_data.column_list, alias: text }

    upload_data.column_list.link:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\LinkColumn
        tags:
            - { name: upload_data.column_list, alias: link }

    upload_data.column_list.attribute:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\AttributeColumn
        tags:
            - { name: upload_data.column_list, alias: attribute }

    upload_data.column_list.number_link:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\NumberLinkColumn
        tags:
            - { name: upload_data.column_list, alias: number_link }

    upload_data.column_list.datetime:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\DatetimeColumn
        tags:
            - { name: upload_data.column_list, alias: datetime }

    upload_data.column_list.number:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\NumberColumn
        tags:
            - { name: upload_data.column_list, alias: number }

    upload_data.column_list.action:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\ActionColumn
        tags:
            - { name: upload_data.column_list, alias: action }

    upload_data.csv_reader:
        class: Manuel\Bundle\UploadDataBundle\Data\Reader\CsvReader
        tags:
            - { name: upload_data.reader, route_config: upload_data_upload_read_csv }

    upload_data.excel_reader:
        class: Manuel\Bundle\UploadDataBundle\Data\Reader\ExcelReader
        tags:
            - { name: upload_data.reader, route_config: upload_data_upload_read_excel }

    upload_data.reader_loader:
        class: Manuel\Bundle\UploadDataBundle\Data\Reader\ReaderLoader
#
#    upload_data.twig.callable_extension:
#        class: Manuel\Bundle\UploadDataBundle\Twig\Extention\CallbackExtension
#        tags:
#            - { name: twig.extension }
#
#    upload_config_test:
#        class: Manuel\Bundle\UploadDataBundle\VentasConfig
#        tags:
#            - { name: upload_data.config, id: ventas, label: Ventas }

#    upload_data.block.column_list:
#        class: Manuel\Bundle\UploadDataBundle\Block\ColumnListBlockService
#        arguments: [upload_data.block.column_list, @templating]
#        tags:
#            - { name: sonata.block }
#
#    upload_data.block.header_column_list:
#        class: Manuel\Bundle\UploadDataBundle\Block\HeaderColumnListBlockService
#        arguments: [upload_data.block.header_column_list, @templating]
#        tags:
#            - { name: sonata.block }

    upload_data.block.upload_list:
        class: Manuel\Bundle\UploadDataBundle\Block\UploadListBlockService
        arguments: [upload_data.block.upload_list, @templating]
        calls:
            - [setUploadTypes, [%upload_data.upload_types%]]
        tags:
            - { name: sonata.block }

    upload_data.upload_repository:
        class: Manuel\Bundle\UploadDataBundle\Entity\UploadRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [UploadDataBundle:Upload]

    upload_data.command.process_action:
        class: Manuel\Bundle\UploadDataBundle\Command\ProcessActionCommand
        arguments:
            - @upload_data.config_provider
            - @upload_data.upload_repository
            - @?logger
        tags:
            - { name: console.command }

    upload_data.file_helper.local:
        class: Manuel\Bundle\UploadDataBundle\Data\LocalUploadedFileHelper
        public: false

    upload_data.headers_matcher.excel:
        class: Manuel\Bundle\UploadDataBundle\Data\Reader\ExcelHeadersMatcher
        arguments:
            - "@upload_data.excel_reader"

    upload_data.twig.extension.upload:
        class: Manuel\Bundle\UploadDataBundle\Twig\Extention\UploadDataExtension
        public: false
        arguments:
            - "@upload_data.config_provider"
        tags:
            - { name: twig.extension }