services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Manuel\Bundle\UploadDataBundle\ConfigProvider:
        arguments:
            - !tagged_locator { tag: 'upload_data.config', index_by: 'id' }

    upload_data.column_list_factory:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\ColumnFactory
        arguments:
            - !tagged_locator { tag: 'upload_data.column_list', index_by: 'alias' }

    upload_data.list_mapper:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ListMapper
        arguments: ['@upload_data.column_list_factory']

    upload_data.column_list.text:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\TextColumn
        tags:
            - { name: upload_data.column_list, alias: text }

    upload_data.column_list.link:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\LinkColumn
        tags:
            - { name: upload_data.column_list, alias: link }

    upload_data.column_list.attribute:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\AttributeColumn
        tags:
            - { name: upload_data.column_list, alias: attribute }

    upload_data.column_list.number_link:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\NumberLinkColumn
        tags:
            - { name: upload_data.column_list, alias: number_link }

    upload_data.column_list.datetime:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\DatetimeColumn
        tags:
            - { name: upload_data.column_list, alias: datetime }

    upload_data.column_list.number:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\NumberColumn
        tags:
            - { name: upload_data.column_list, alias: number }

    upload_data.column_list.action:
        class: Manuel\Bundle\UploadDataBundle\Mapper\ColumnList\ActionColumn
        tags:
            - { name: upload_data.column_list, alias: action }

    upload_data.csv_reader:
        class: Manuel\Bundle\UploadDataBundle\Data\Reader\CsvReader
        tags:
            - { name: upload_data.reader, route_config: upload_data_upload_read_csv }

    Manuel\Bundle\UploadDataBundle\Data\Reader\ExcelReader:
        tags:
            - { name: upload_data.reader, route_config: upload_data_upload_read_excel }

    Manuel\Bundle\UploadDataBundle\Data\Reader\ReaderLoader: ~

    Manuel\Bundle\UploadDataBundle\Entity\UploadRepository:
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['UploadDataBundle:Upload']

    upload_data.command.process_action:
        class: Manuel\Bundle\UploadDataBundle\Command\ProcessActionCommand
        tags:
            - { name: console.command }

    upload_data.file_helper.local:
        class: Manuel\Bundle\UploadDataBundle\Data\LocalUploadedFileHelper

    upload_data.headers_matcher.excel:
        class: Manuel\Bundle\UploadDataBundle\Data\Reader\ExcelHeadersMatcher

    upload_data.twig.extension.upload:
        class: Manuel\Bundle\UploadDataBundle\Twig\Extention\UploadDataExtension
        public: false
        tags:
            - { name: twig.extension }

    upload_data.constraint.validator.entity_exists:
        class: Manuel\Bundle\UploadDataBundle\Validator\Constraint\EntityExistsValidator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@property_accessor"
        tags:
            - { name: validator.constraint_validator, alias: 'upload_data.entity_exists' }

    upload_data.profiler.exception:
        class: Manuel\Bundle\UploadDataBundle\Profiler\ExceptionProfiler
        public: false
        arguments:
            - "@event_dispatcher"
            - "@?profiler"
