<?php

namespace Manuel\Bundle\UploadDataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UploadedItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadedItemRepository extends EntityRepository
{
    public function getQueryByUpload($upload)
    {
        return $this->createQueryBuilder('uploaded_item')
            ->where('uploaded_item.upload = :upload')
            ->setParameter('upload', $upload);
    }
}
