<?php

namespace Manuelj555\Bundle\UploadDataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadRepository extends EntityRepository
{
    public function getQueryForType($type)
    {
        return $this->createQueryBuilder('upload')
            ->where('upload.type = :type')
            ->setParameter('type', $type);
    }
}
