<?php
/**
 * 28/09/14
 * upload
 */

namespace Manuel\Bundle\UploadDataBundle\Mapper\ColumnList;

use Symfony\Component\OptionsResolver\OptionsResolverInterface;


/**
 * @autor Manuel Aguirre <programador.manuel@gmail.com>
 */
class DatetimeColumn extends AbstractColumn
{

    public function getType()
    {
        return 'datetime';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults(array(
            'format' => 'Y-m-d H:i:s',
            'template' => '@UploadData/Default/column_datetime.html.twig',
        ));
    }


}