<?php
/**
 * 28/09/14
 * upload
 */

namespace Manuel\Bundle\UploadDataBundle\Mapper\ColumnList;

use Symfony\Component\OptionsResolver\OptionsResolverInterface;


/**
 * @autor Manuel Aguirre <programador.manuel@gmail.com>
 */
class LinkColumn extends AbstractColumn
{

    public function getType()
    {
        return 'link';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults(array(
            'route' => null,
            'url' => null,
            'attr' => array(),
            'template' => '@UploadData/Default/column_link.html.twig',
        ));

        $resolver->setOptional(array('condition'));
        $resolver->setAllowedTypes(array(
            'condition' => 'Closure',
        ));
    }


}